# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nepes\OneDrive - 네패스\바탕 화면\PROJECT_GIT\RPA_Monitoring\VEGA_개발\RPA_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TOTAL(object):
    def setupUi(self, TOTAL):
        TOTAL.setObjectName("TOTAL")
        TOTAL.resize(1355, 905)
        self.centralwidget = QtWidgets.QWidget(TOTAL)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, -40, 1341, 891))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    background-color: #F0F0F0;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #E0E0E0;\n"
"    padding: 8px;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #F0F0F0;\n"
"    border-bottom: 1px solid #F0F0F0;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #F8F8F8;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.Main_tab = QtWidgets.QWidget()
        self.Main_tab.setObjectName("Main_tab")
        self.label_3 = QtWidgets.QLabel(self.Main_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 1300, 94))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #c7c1c1;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 25pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 70px;\n"
"    max-height: 70px;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.PUSH_MONITORING = QtWidgets.QPushButton(self.Main_tab)
        self.PUSH_MONITORING.setGeometry(QtCore.QRect(1140, 30, 161, 91))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PUSH_MONITORING.setFont(font)
        self.PUSH_MONITORING.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #7ee137, stop:1 #dadbde);\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 3px 0 rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"    border: 1px solid #3a3939;\n"
"    box-shadow: 0 1px 0 rgba(0,0,0,0.1);\n"
"    transform: translateY(2px);\n"
"}\n"
"")
        self.PUSH_MONITORING.setObjectName("PUSH_MONITORING")
        self.PUSH_RETEST = QtWidgets.QPushButton(self.Main_tab)
        self.PUSH_RETEST.setGeometry(QtCore.QRect(120, 740, 1050, 120))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(40)
        self.PUSH_RETEST.setFont(font)
        self.PUSH_RETEST.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #7ee137, stop:1 #dadbde);\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 3px 0 rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"    border: 1px solid #3a3939;\n"
"    box-shadow: 0 1px 0 rgba(0,0,0,0.1);\n"
"    transform: translateY(2px);\n"
"}\n"
"")
        self.PUSH_RETEST.setObjectName("PUSH_RETEST")
        self.PUSH_LAST_DIE = QtWidgets.QPushButton(self.Main_tab)
        self.PUSH_LAST_DIE.setGeometry(QtCore.QRect(120, 590, 1050, 120))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(40)
        self.PUSH_LAST_DIE.setFont(font)
        self.PUSH_LAST_DIE.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #7ee137, stop:1 #dadbde);\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 3px 0 rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"    border: 1px solid #3a3939;\n"
"    box-shadow: 0 1px 0 rgba(0,0,0,0.1);\n"
"    transform: translateY(2px);\n"
"}\n"
"")
        self.PUSH_LAST_DIE.setObjectName("PUSH_LAST_DIE")
        self.PUSH_LOT_CHANGE = QtWidgets.QPushButton(self.Main_tab)
        self.PUSH_LOT_CHANGE.setGeometry(QtCore.QRect(120, 290, 1050, 120))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(40)
        self.PUSH_LOT_CHANGE.setFont(font)
        self.PUSH_LOT_CHANGE.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #7ee137, stop:1 #dadbde);\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 3px 0 rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"    border: 1px solid #3a3939;\n"
"    box-shadow: 0 1px 0 rgba(0,0,0,0.1);\n"
"    transform: translateY(2px);\n"
"}\n"
"")
        self.PUSH_LOT_CHANGE.setObjectName("PUSH_LOT_CHANGE")
        self.PUSH_MONITORING_DATA = QtWidgets.QPushButton(self.Main_tab)
        self.PUSH_MONITORING_DATA.setGeometry(QtCore.QRect(120, 140, 1050, 120))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(40)
        self.PUSH_MONITORING_DATA.setFont(font)
        self.PUSH_MONITORING_DATA.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #7ee137, stop:1 #dadbde);\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 3px 0 rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"    border: 1px solid #3a3939;\n"
"    box-shadow: 0 1px 0 rgba(0,0,0,0.1);\n"
"    transform: translateY(2px);\n"
"}\n"
"")
        self.PUSH_MONITORING_DATA.setObjectName("PUSH_MONITORING_DATA")
        self.PUSH_CONVERSION = QtWidgets.QPushButton(self.Main_tab)
        self.PUSH_CONVERSION.setGeometry(QtCore.QRect(120, 440, 1050, 120))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(40)
        self.PUSH_CONVERSION.setFont(font)
        self.PUSH_CONVERSION.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #7ee137, stop:1 #dadbde);\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 3px 0 rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"    border: 1px solid #3a3939;\n"
"    box-shadow: 0 1px 0 rgba(0,0,0,0.1);\n"
"    transform: translateY(2px);\n"
"}\n"
"")
        self.PUSH_CONVERSION.setObjectName("PUSH_CONVERSION")
        self.PUSH_USER_INFO = QtWidgets.QPushButton(self.Main_tab)
        self.PUSH_USER_INFO.setGeometry(QtCore.QRect(970, 30, 161, 91))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PUSH_USER_INFO.setFont(font)
        self.PUSH_USER_INFO.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #7ee137, stop:1 #dadbde);\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    box-shadow: 0 3px 0 rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"    border: 1px solid #3a3939;\n"
"    box-shadow: 0 1px 0 rgba(0,0,0,0.1);\n"
"    transform: translateY(2px);\n"
"}\n"
"")
        self.PUSH_USER_INFO.setObjectName("PUSH_USER_INFO")
        self.tabWidget.addTab(self.Main_tab, "")
        self.Reference_tab = QtWidgets.QWidget()
        self.Reference_tab.setObjectName("Reference_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Reference_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 60, 1291, 761))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PC_TABLE = QtWidgets.QTableView(self.gridLayoutWidget)
        self.PC_TABLE.setStyleSheet("QTableView {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #f0f0f0, stop:1 #d0d0d0);\n"
"    border: 2px solid #a0a0a0;\n"
"    border-radius: 10px;\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4a90d9, stop:1 #3570b0);\n"
"    font: 75 8pt \"맑은 고딕\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #5c5c5c, stop:1 #353535);\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #2c2c2c;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4a90d9, stop:1 #3570b0);\n"
"    color: white;\n"
"}\n"
"")
        self.PC_TABLE.setObjectName("PC_TABLE")
        self.gridLayout_2.addWidget(self.PC_TABLE, 1, 1, 1, 1)
        self.PIB_TABLE = QtWidgets.QTableView(self.gridLayoutWidget)
        self.PIB_TABLE.setStyleSheet("QTableView {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #f0f0f0, stop:1 #d0d0d0);\n"
"    border: 2px solid #a0a0a0;\n"
"    border-radius: 10px;\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4a90d9, stop:1 #3570b0);\n"
"    font: 75 8pt \"맑은 고딕\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #5c5c5c, stop:1 #353535);\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #2c2c2c;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4a90d9, stop:1 #3570b0);\n"
"    color: white;\n"
"}\n"
"")
        self.PIB_TABLE.setObjectName("PIB_TABLE")
        self.gridLayout_2.addWidget(self.PIB_TABLE, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #c7c1c1;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.INSERT_BUTTON_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.INSERT_BUTTON_1.setStyleSheet("QPushButton {\n"
"    /* 위에서 아래로 그라데이션 배경 설정 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #f6f7fa, stop:1 #dadbde);\n"
"\n"
"    /* 버튼 테두리 설정 */\n"
"    border: 1px solid #8f8f91;\n"
"\n"
"    /* 모서리를 둥글게 만듦 */\n"
"    border-radius: 3px;\n"
"\n"
"    /* 버튼 내부 여백 */\n"
"    padding: 5px;\n"
"\n"
"    /* 최소 크기 설정 */\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* 호버 시 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #dadbde, stop:1 #7ee137);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* 눌렀을 때 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #d7d8db, stop:1 #7ee137);\n"
"\n"
"    /* 테두리 색상 변경 */\n"
"    border: 1px solid #3a3939;\n"
"}\n"
"")
        self.INSERT_BUTTON_1.setObjectName("INSERT_BUTTON_1")
        self.gridLayout_2.addWidget(self.INSERT_BUTTON_1, 2, 2, 1, 1)
        self.CLOSE_BUTTON_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CLOSE_BUTTON_1.setStyleSheet("QPushButton {\n"
"    /* 위에서 아래로 그라데이션 배경 설정 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #f6f7fa, stop:1 #dadbde);\n"
"\n"
"    /* 버튼 테두리 설정 */\n"
"    border: 1px solid #8f8f91;\n"
"\n"
"    /* 모서리를 둥글게 만듦 */\n"
"    border-radius: 3px;\n"
"\n"
"    /* 버튼 내부 여백 */\n"
"    padding: 5px;\n"
"\n"
"    /* 최소 크기 설정 */\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* 호버 시 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #dadbde, stop:1 #ca0c06);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* 눌렀을 때 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #d7d8db, stop:1 #ca0c06);\n"
"\n"
"    /* 테두리 색상 변경 */\n"
"    border: 1px solid #3a3939;\n"
"}\n"
"")
        self.CLOSE_BUTTON_1.setObjectName("CLOSE_BUTTON_1")
        self.gridLayout_2.addWidget(self.CLOSE_BUTTON_1, 3, 2, 1, 1)
        self.LOT_TABLE = QtWidgets.QTableView(self.gridLayoutWidget)
        self.LOT_TABLE.setStyleSheet("QTableView {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #f0f0f0, stop:1 #d0d0d0);\n"
"    border: 2px solid #a0a0a0;\n"
"    border-radius: 10px;\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4a90d9, stop:1 #3570b0);\n"
"    font: 75 8pt \"맑은 고딕\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #5c5c5c, stop:1 #353535);\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #2c2c2c;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4a90d9, stop:1 #3570b0);\n"
"    color: white;\n"
"}\n"
"")
        self.LOT_TABLE.setObjectName("LOT_TABLE")
        self.gridLayout_2.addWidget(self.LOT_TABLE, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #c7c1c1;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #c7c1c1;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.tabWidget.addTab(self.Reference_tab, "")
        self.Monitor_tab = QtWidgets.QWidget()
        self.Monitor_tab.setObjectName("Monitor_tab")
        self.textBrowser = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser.setGeometry(QtCore.QRect(260, 180, 671, 74))
        self.textBrowser.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #bdeaf4;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(260, 270, 671, 74))
        self.textBrowser_2.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #bdeaf4;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_3.setGeometry(QtCore.QRect(260, 360, 671, 74))
        self.textBrowser_3.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #bdeaf4;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_4.setGeometry(QtCore.QRect(260, 450, 671, 74))
        self.textBrowser_4.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #bdeaf4;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_5.setGeometry(QtCore.QRect(260, 540, 671, 74))
        self.textBrowser_5.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #bdeaf4;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_6.setGeometry(QtCore.QRect(260, 630, 671, 74))
        self.textBrowser_6.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #bdeaf4;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_7.setGeometry(QtCore.QRect(260, 720, 671, 74))
        self.textBrowser_7.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #bdeaf4;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.PUSH_HOME = QtWidgets.QPushButton(self.Monitor_tab)
        self.PUSH_HOME.setGeometry(QtCore.QRect(970, 170, 301, 81))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PUSH_HOME.setFont(font)
        self.PUSH_HOME.setStyleSheet("QPushButton {\n"
"    /* 위에서 아래로 그라데이션 배경 설정 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #f5af46, stop:1 #dadbde);\n"
"\n"
"    /* 버튼 테두리 설정 */\n"
"    border: 1px solid #8f8f91;\n"
"\n"
"    /* 모서리를 둥글게 만듦 */\n"
"    border-radius: 6px;\n"
"\n"
"    /* 버튼 내부 여백 */\n"
"    padding: 5px;\n"
"\n"
"    /* 최소 크기 설정 */\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"\n"
"    /* 그림자 효과 추가 */\n"
"    box-shadow: 0px 3px 5px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* 호버 시 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* 눌렀을 때 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"\n"
"    /* 테두리 색상 변경 */\n"
"    border: 1px solid #3a3939;\n"
"}\n"
"")
        self.PUSH_HOME.setObjectName("PUSH_HOME")
        self.PUSH_CLEAR = QtWidgets.QPushButton(self.Monitor_tab)
        self.PUSH_CLEAR.setGeometry(QtCore.QRect(970, 270, 301, 81))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PUSH_CLEAR.setFont(font)
        self.PUSH_CLEAR.setStyleSheet("QPushButton {\n"
"    /* 위에서 아래로 그라데이션 배경 설정 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #f5af46, stop:1 #dadbde);\n"
"\n"
"    /* 버튼 테두리 설정 */\n"
"    border: 1px solid #8f8f91;\n"
"\n"
"    /* 모서리를 둥글게 만듦 */\n"
"    border-radius: 6px;\n"
"\n"
"    /* 버튼 내부 여백 */\n"
"    padding: 5px;\n"
"\n"
"    /* 최소 크기 설정 */\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"\n"
"    /* 그림자 효과 추가 */\n"
"    box-shadow: 0px 3px 5px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* 호버 시 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* 눌렀을 때 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"\n"
"    /* 테두리 색상 변경 */\n"
"    border: 1px solid #3a3939;\n"
"}\n"
"")
        self.PUSH_CLEAR.setObjectName("PUSH_CLEAR")
        self.pushButton_2 = QtWidgets.QPushButton(self.Monitor_tab)
        self.pushButton_2.setGeometry(QtCore.QRect(970, 370, 301, 81))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    /* 위에서 아래로 그라데이션 배경 설정 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #ca0c06, stop:1 #dadbde);\n"
"\n"
"    /* 버튼 테두리 설정 */\n"
"    border: 1px solid #8f8f91;\n"
"\n"
"    /* 모서리를 둥글게 만듦 (6픽셀 반경) */\n"
"    border-radius: 6px;\n"
"\n"
"    /* 버튼 내부 여백 */\n"
"    padding: 5px;\n"
"\n"
"    /* 최소 크기 설정 */\n"
"    min-width: 50px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* 호버 시 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #f6f7fa, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* 눌렀을 때 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"\n"
"    /* 테두리 색상 변경 */\n"
"    border: 1px solid #3a3939;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.EQP_ID = QtWidgets.QLineEdit(self.Monitor_tab)
        self.EQP_ID.setGeometry(QtCore.QRect(60, 70, 641, 91))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.EQP_ID.setFont(font)
        self.EQP_ID.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #c7c1c1;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 45pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 70px;\n"
"}\n"
"")
        self.EQP_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.EQP_ID.setObjectName("EQP_ID")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_8.setGeometry(QtCore.QRect(20, 190, 241, 71))
        self.textBrowser_8.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_9.setGeometry(QtCore.QRect(20, 280, 241, 71))
        self.textBrowser_9.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_10.setGeometry(QtCore.QRect(20, 370, 241, 71))
        self.textBrowser_10.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_11.setGeometry(QtCore.QRect(20, 460, 241, 71))
        self.textBrowser_11.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_12.setGeometry(QtCore.QRect(20, 550, 241, 71))
        self.textBrowser_12.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_13.setGeometry(QtCore.QRect(20, 640, 241, 71))
        self.textBrowser_13.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.Monitor_tab)
        self.textBrowser_14.setGeometry(QtCore.QRect(20, 730, 241, 71))
        self.textBrowser_14.setStyleSheet("QTextBrowser {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.RPA_START_3 = QtWidgets.QPushButton(self.Monitor_tab)
        self.RPA_START_3.setGeometry(QtCore.QRect(970, 70, 301, 81))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RPA_START_3.setFont(font)
        self.RPA_START_3.setStyleSheet("QPushButton {\n"
"    /* 위에서 아래로 그라데이션 배경 설정 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #7ee137, stop:1 #dadbde);\n"
"\n"
"    /* 버튼 테두리 설정 */\n"
"    border: 1px solid #8f8f91;\n"
"\n"
"    /* 모서리를 둥글게 만듦 */\n"
"    border-radius: 6px;\n"
"\n"
"    /* 버튼 내부 여백 */\n"
"    padding: 5px;\n"
"\n"
"    /* 최소 크기 설정 */\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* 호버 시 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #dadbde, stop:1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* 눌렀을 때 배경색 변경 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 #d7d8db, stop:1 #f6f7fa);\n"
"\n"
"    /* 테두리 색상 변경 */\n"
"    border: 1px solid #3a3939;\n"
"}\n"
"")
        self.RPA_START_3.setObjectName("RPA_START_3")
        self.STATUS_ID = QtWidgets.QLineEdit(self.Monitor_tab)
        self.STATUS_ID.setGeometry(QtCore.QRect(710, 70, 221, 91))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.STATUS_ID.setFont(font)
        self.STATUS_ID.setStyleSheet("QWidget {\n"
"    /* 배경색 설정 */\n"
"    background-color: #c7c1c1;\n"
"\n"
"    /* 테두리 설정 */\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px; /* 둥근 모서리 */\n"
"\n"
"    /* 내부 여백 설정 */\n"
"    padding: 10px;\n"
"\n"
"    /* 텍스트 기본 설정 */\n"
"    font: bold 20pt \"굴림\"; /* 폰트 설정 및 bold 적용 */\n"
"    color: #000000; /* 텍스트 색상 */\n"
"\n"
"    /* 최소 및 최대 높이 설정 */\n"
"    min-height: 50px;\n"
"    max-height: 70px;\n"
"}\n"
"")
        self.STATUS_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.STATUS_ID.setObjectName("STATUS_ID")
        self.tabWidget.addTab(self.Monitor_tab, "")
        TOTAL.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TOTAL)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1355, 21))
        self.menubar.setObjectName("menubar")
        TOTAL.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TOTAL)
        self.statusbar.setObjectName("statusbar")
        TOTAL.setStatusBar(self.statusbar)

        self.retranslateUi(TOTAL)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TOTAL)

    def retranslateUi(self, TOTAL):
        _translate = QtCore.QCoreApplication.translate
        TOTAL.setWindowTitle(_translate("TOTAL", "MainWindow"))
        self.label_3.setText(_translate("TOTAL", "▣ RPA 실행 항목"))
        self.PUSH_MONITORING.setText(_translate("TOTAL", "진행정보_확인"))
        self.PUSH_RETEST.setText(_translate("TOTAL", "RETEST"))
        self.PUSH_LAST_DIE.setText(_translate("TOTAL", "LAST_DIE"))
        self.PUSH_LOT_CHANGE.setText(_translate("TOTAL", "LOT_CHANGE"))
        self.PUSH_MONITORING_DATA.setText(_translate("TOTAL", "MONITORING"))
        self.PUSH_CONVERSION.setText(_translate("TOTAL", "CONVERSION"))
        self.PUSH_USER_INFO.setText(_translate("TOTAL", "사용자 등록"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main_tab), _translate("TOTAL", "Main"))
        self.label_2.setText(_translate("TOTAL", "LOT"))
        self.INSERT_BUTTON_1.setText(_translate("TOTAL", "DATA 입력"))
        self.CLOSE_BUTTON_1.setText(_translate("TOTAL", "CLOSE"))
        self.label_4.setText(_translate("TOTAL", "PROBE CARD"))
        self.label_5.setText(_translate("TOTAL", "PIB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Reference_tab), _translate("TOTAL", "Reference"))
        self.PUSH_HOME.setText(_translate("TOTAL", "HOME"))
        self.PUSH_CLEAR.setText(_translate("TOTAL", "CLEAR"))
        self.pushButton_2.setText(_translate("TOTAL", "CLOSE"))
        self.textBrowser_8.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">DEVICE :</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">LOT-ID :</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">STEP-ID :</span></p></body></html>"))
        self.textBrowser_11.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">PC-ID :</span></p></body></html>"))
        self.textBrowser_12.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">PB-ID :</span></p></body></html>"))
        self.textBrowser_13.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">USER-ID :</span></p></body></html>"))
        self.textBrowser_14.setHtml(_translate("TOTAL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">COMMENT :</span></p></body></html>"))
        self.RPA_START_3.setText(_translate("TOTAL", "RPA_START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Monitor_tab), _translate("TOTAL", "Monitor"))
